spring:
  datasource:
    name: cattle_house
    url: jdbc:mysql://localhost:3306/cattle_house
    username: root
    password: abc=1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cattle.house.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
